[package]
name = "lumi-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1.6"
async-executor = "1.4"
futures-lite = "1.12"
num_cpus = "1.13"
