[package]
name = "lumi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["lumi-macro"]

[dev-dependencies]
futures-lite = "1.12"
winit = "0.27"

[dependencies]
lumi-macro = { path = "lumi-macro", version = "0.1" }

anyhow = "1.0"
bytemuck = { version = "1.12", features = ["derive"] }
encase = { version = "0.3", features = ["glam"] }
glam = { version = "0.21", features = ["bytemuck"] }
image = { version = "0.24", optional = true }
mikktspace = { version = "0.3", default-features = false, features = ["glam"] }
naga = { version = "0.9", features = ["glsl-in", "wgsl-out"] }
once_cell = "1.15"
thiserror = "1.0"
wgpu = "0.13"
uuid = { version = "1.1", features = ["v4"] }

[features]
default = ["image"]
image = ["dep:image"]
