[package]
name = "lumi"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dev-dependencies]
criterion = "0.3"
egui = "0.19.0"
egui_wgpu_backend = "0.20"
egui_winit_platform = "0.16"
futures-lite = "1.12"
winit = "0.27"

[dependencies]
lumi-assets = { path = "crates/lumi-assets", version = "0.1.0" }
lumi-bake = { path = "crates/lumi-bake", version = "0.1.0" }
lumi-bind = { path = "crates/lumi-bind", version = "0.1.0" }
lumi-core = { path = "crates/lumi-core", version = "0.1.0", default-features = false, features = ["image"] }
lumi-id = { path = "crates/lumi-id", version = "0.1.0" }
lumi-macro = { path = "crates/lumi-macro", version = "0.1.0" }
lumi-material = { path = "crates/lumi-material", version = "0.1.0", default-features = false, optional = true }
lumi-mesh = { path = "crates/lumi-mesh", version = "0.1.0" }
lumi-renderer = { path = "crates/lumi-renderer", version = "0.1.0" }
lumi-shader = { path = "crates/lumi-shader", version = "0.1.0" }
lumi-task = { path = "crates/lumi-task", version = "0.1.0" }
lumi-util = { path = "crates/lumi-util", version = "0.1.0" }
lumi-world = { path = "crates/lumi-world", version = "0.1.0" }

tracing-log = "0.1"

[features]
default = ["material", "assets"]
material = ["lumi-material"]
assets = ["lumi-core/assets", "lumi-material/assets"]

[[bench]]
name = "key_map"
harness = false

[[bench]]
name = "resources"
harness = false

[[bench]]
name = "id_map"
harness = false
