[package]
name = "lumi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["lumi-macro", "lumi-bake"]

[dev-dependencies]
egui = "0.19.0"
egui_wgpu_backend = "0.19"
egui_winit_platform = "0.16"
env_logger = "0.9"
futures-lite = "1.12"
winit = "0.27"

[dependencies]
lumi-bake = { path = "lumi-bake", version = "0.1.0" }
lumi-macro = { path = "lumi-macro", version = "0.1.0" }

ahash = "0.8"
anyhow = "1.0"
bytemuck = { version = "1.12", features = ["derive"] }
encase = { version = "0.3", features = ["glam"] }
glam = { version = "0.21", features = ["bytemuck"] }
gltf = { version = "1.0", optional = true }
image = { version = "0.24", optional = true }
log = "0.4"
mikktspace = { version = "0.3", default-features = false, features = ["glam"] }
naga = { version = "0.9", features = ["glsl-in", "wgsl-out"] }
once_cell = "1.15"
thiserror = "1.0"
wgpu = "0.13"
uuid = { version = "1.1", features = ["v4"] }

[features]
default = ["gltf", "image"]
gltf = ["dep:gltf", "image"]
image = ["dep:image", "lumi-bake/image"]
load-shaders = []
