[package]
name = "lumi-bounds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.lumi-util]
path = "../lumi-util"
version = "0.1.0"
default-features = false
features = ["math"]
